name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [ main ]

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false

      - name: Deploy to Azure Static Web Apps (no build)
        uses: Azure/static-web-apps-deploy@v1
        with:
          # >>> PASTIKAN SECRET INI DI-UPDATE DENGAN TOKEN BARU <<<
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_LIVELY_PLANT_05CE28E00 }}
          action: upload

          # lokasi file statis (pilih salah satu)
          app_location: "."            # kalau index.html ada di root
          output_location: "."         # tidak ada proses build

          # matikan proses build & API
          skip_app_build: true
          skip_api_build: true
          app_build_command: "echo no build"
          api_build_command: "echo no api"

          # matikan Data API default supaya tidak cari 'swa-db-connections'
          data_api_location: ""        # <— penting

          # (opsional) set secara eksplisit
          production_branch: "main"

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: close
